(function (global) {
  'use strict';
  const MIN_DURATION = 5;
  const MAX_DURATION = 120;
  const TYPES = {
    summary: ['Resumo geral da campanha', 'Indicadores gerais e liderança atual.'],
    cards: ['Pódio por valor', 'Destaques em cartões para leitura à distância.'],
    ranking: ['Ranking por valor', 'Tabela de classificação por valor vendido.'],
    products: ['Ranking por quantidade', 'Classificação pela quantidade HENGST.'],
    growth: ['Crescimento mensal', 'Comparativo com a base histórica.']
  };
  const DEFAULT_SCENES = Object.keys(TYPES).map((type, index) => ({ id:type, type, nome:TYPES[type][0], ativa:true, ordem:index+1, duracao:12, quantidadeExibida:type==='cards'?4:8, metrica:type==='products'?'quantidade':'valor', animacao:'fade', modo:'completo', titulo:'', filial:'', vendedor:'', mostrarPosicao:true, mostrarFoto:true, mostrarMeta:true, mostrarCrescimento:true, mostrarFilial:true, mostrarQuantidade:true, mostrarValor:true, mostrarParticipacao:true }));
  const DEFAULT_ALERTS = [['last-sale','Última venda',1,30],['new-leader','Novo líder',1,300],['podium-change','Alteração no pódio',2,300],['top-3','Entrada no TOP 3',2,300],['top-12','Entrada no TOP 12',3,300],['individual-goal','Meta individual atingida',1,300],['campaign-25','Campanha atingiu 25%',3,300],['campaign-50','Campanha atingiu 50%',2,300],['campaign-75','Campanha atingiu 75%',2,300],['campaign-100','Meta geral atingida',1,300]].map(([id,nome,prioridade,intervaloMinimo]) => ({id,nome,ativo:true,duracao:6,intervaloMinimo,prioridade,animacao:'pulse',som:prioridade<=2,ultimaExibicao:null}));
  const clone = value => JSON.parse(JSON.stringify(value));
  const clamp = (value,min,max,fallback) => { const number=Number(value); return Number.isFinite(number)?Math.min(max,Math.max(min,number)):fallback; };
  function uniqueId(base, used) { const root=String(base||'scene').replace(/[^a-z0-9_-]/gi,'-').toLowerCase(); let id=root,suffix=2; while(used.has(id)) id=`${root}-${suffix++}`; used.add(id); return id; }
  function normalizeScene(input,index,used) { const legacy=typeof input==='string'?input:input?.type||input?.id; const type=TYPES[legacy]?legacy:'summary'; const source=typeof input==='object'&&input?input:{}; const defaults=DEFAULT_SCENES.find(scene=>scene.type===type)||DEFAULT_SCENES[0]; return {...clone(defaults),...source,id:uniqueId(source.id||legacy||`scene-${index+1}`,used),type,nome:String(source.nome||TYPES[type][0]).slice(0,80),ativa:source.ativa!==false,ordem:index+1,duracao:clamp(source.duracao,MIN_DURATION,MAX_DURATION,defaults.duracao),quantidadeExibida:clamp(source.quantidadeExibida,1,14,defaults.quantidadeExibida),metrica:source.metrica==='quantidade'?'quantidade':'valor',animacao:['fade','slide','none'].includes(source.animacao)?source.animacao:'fade',modo:source.modo==='compacto'?'compacto':'completo',titulo:String(source.titulo||'').slice(0,80)}; }
  function normalizeScenes(input) { const source=Array.isArray(input)&&input.length?input:DEFAULT_SCENES; const used=new Set(); return source.map((scene,index)=>normalizeScene(scene,index,used)); }
  function normalizeAlerts(input) { const supplied=new Map((Array.isArray(input)?input:[]).map(alert=>[alert.id,alert])); return DEFAULT_ALERTS.map(base=>{const source=supplied.get(base.id)||{};return {...base,...source,ativo:source.ativo!==false,duracao:clamp(source.duracao,5,30,base.duracao),intervaloMinimo:clamp(source.intervaloMinimo,30,86400,base.intervaloMinimo),prioridade:clamp(source.prioridade,1,5,base.prioridade),som:source.som??base.som};}); }
  function normalizeSettings(settings={}) { return {interval:clamp(settings.interval,5,120,12),rows:[5,8,10,12,14].includes(Number(settings.rows))?Number(settings.rows):8,metric:settings.metric==='quantidade'?'quantidade':'valor',scenes:normalizeScenes(settings.scenes),alerts:normalizeAlerts(settings.alerts),alertHistory:settings.alertHistory&&typeof settings.alertHistory==='object'?settings.alertHistory:{},participants:Array.isArray(settings.participants)?[...new Set(settings.participants.map(String).filter(Boolean))]:null}; }
  const activeScenes = settings => normalizeScenes(settings?.scenes).filter(scene=>scene.ativa).sort((a,b)=>a.ordem-b.ordem);
  const escapeText = value => String(value??'').replace(/[&<>]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[char]));
  const escapeAttr = value => escapeText(value).replace(/"/g,'&quot;');
  function mountEditor(container,settings,onPreview){
    if(!container)return null; let draft=normalizeScenes(settings.scenes),dragged=-1;
    const orders=()=>draft.forEach((scene,index)=>scene.ordem=index+1);
    const render=()=>{container.innerHTML=draft.map((scene,index)=>`<article class="tv-editor-scene ${scene.ativa?'is-active':'is-inactive'}" draggable="true" data-scene-index="${index}"><div class="tv-editor-scene-head"><span class="tv-editor-drag" title="Arraste para ordenar">⋮⋮</span><div><strong>${escapeText(scene.nome)}</strong><small>${escapeText(TYPES[scene.type][1])}</small></div><label class="tv-editor-toggle"><input type="checkbox" data-field="ativa" ${scene.ativa?'checked':''}><span>${scene.ativa?'Ativa':'Inativa'}</span></label></div><div class="tv-editor-grid"><label>Título personalizado<input data-field="titulo" value="${escapeAttr(scene.titulo)}" placeholder="${escapeAttr(scene.nome)}"></label><label>Duração (5–120 s)<input type="number" min="5" max="120" data-field="duracao" value="${scene.duracao}"></label><label>Quantidade exibida<input type="number" min="1" max="14" data-field="quantidadeExibida" value="${scene.quantidadeExibida}"></label><label>Métrica<select data-field="metrica"><option value="valor" ${scene.metrica==='valor'?'selected':''}>Valor</option><option value="quantidade" ${scene.metrica==='quantidade'?'selected':''}>Quantidade</option></select></label><label>Animação<select data-field="animacao"><option value="fade" ${scene.animacao==='fade'?'selected':''}>Fade</option><option value="slide" ${scene.animacao==='slide'?'selected':''}>Deslizar</option><option value="none" ${scene.animacao==='none'?'selected':''}>Sem animação</option></select></label><label>Exibição<select data-field="modo"><option value="completo" ${scene.modo==='completo'?'selected':''}>Completa</option><option value="compacto" ${scene.modo==='compacto'?'selected':''}>Compacta</option></select></label></div><div class="tv-editor-flags">${['mostrarPosicao:Posição','mostrarFoto:Foto','mostrarMeta:Meta','mostrarCrescimento:Crescimento','mostrarFilial:Filial','mostrarQuantidade:Quantidade','mostrarValor:Valor','mostrarParticipacao:Participação'].map(item=>{const [field,label]=item.split(':');return`<label><input type="checkbox" data-field="${field}" ${scene[field]!==false?'checked':''}>${label}</label>`;}).join('')}</div><div class="tv-editor-actions"><button type="button" class="secondary" data-action="first">Início</button><button type="button" class="secondary" data-action="up">Subir</button><button type="button" class="secondary" data-action="down">Descer</button><button type="button" class="secondary" data-action="last">Final</button><button type="button" class="secondary" data-action="duplicate">Duplicar</button><button type="button" class="secondary" data-action="preview">Pré-visualizar</button></div></article>`).join('');};
    const move=(from,to)=>{if(to<0||to>=draft.length||from===to)return;const [scene]=draft.splice(from,1);draft.splice(to,0,scene);orders();render();};
    container.onchange=event=>{const card=event.target.closest('[data-scene-index]'),field=event.target.dataset.field;if(!card||!field)return;const scene=draft[Number(card.dataset.sceneIndex)];scene[field]=event.target.type==='checkbox'?event.target.checked:event.target.value;if(field==='duracao')scene[field]=clamp(scene[field],5,120,12);if(field==='quantidadeExibida')scene[field]=clamp(scene[field],1,14,8);render();};
    container.onclick=event=>{const button=event.target.closest('[data-action]'),card=event.target.closest('[data-scene-index]');if(!button||!card)return;const index=Number(card.dataset.sceneIndex),action=button.dataset.action;if(action==='up')move(index,index-1);if(action==='down')move(index,index+1);if(action==='first')move(index,0);if(action==='last')move(index,draft.length-1);if(action==='duplicate'){const used=new Set(draft.map(scene=>scene.id));draft.splice(index+1,0,normalizeScene({...draft[index],id:`${draft[index].id}-copy`,nome:`${draft[index].nome} (cópia)`},index+1,used));orders();render();}if(action==='preview')onPreview?.(draft[index]);};
    container.ondragstart=event=>{dragged=Number(event.target.closest('[data-scene-index]')?.dataset.sceneIndex??-1);};container.ondragover=event=>event.preventDefault();container.ondrop=event=>{event.preventDefault();const target=Number(event.target.closest('[data-scene-index]')?.dataset.sceneIndex??-1);if(dragged>=0&&target>=0)move(dragged,target);dragged=-1;};render();return{getScenes:()=>normalizeScenes(draft),reset:scenes=>{draft=normalizeScenes(scenes);render();}};
  }
  function createSyncChannel(onMessage){if(!('BroadcastChannel'in global))return{postMessage(){},close(){}};const channel=new BroadcastChannel('hengst-panel-sync');channel.onmessage=event=>onMessage?.(event.data);return channel;}
  global.HengstTVPhase3={MIN_DURATION,MAX_DURATION,TYPES,DEFAULT_SCENES,DEFAULT_ALERTS,normalizeSettings,normalizeScenes,normalizeAlerts,activeScenes,mountEditor,createSyncChannel,clone};
})(window);
